spring:
  application:
    name: identity-service
  datasource:
    url: "jdbc:mysql://localhost:3306/identity_service"
    password: root
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080
  servlet:
    context-path: /identity

jwt:
  signerKey: "EZlMr8WycQGUTx8N3Fra8NZXY33tDbCOXv40rJ2DCAsMYDlOfP7s46+/E6ksRIeD"
